# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_archive', models.FileField(upload_to='dicom/')),
                ('voxel_file', models.FileField(upload_to='voxels/')),
            ],
        ),
    ]
