# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageseries',
            name='patient_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='imageseries',
            name='series_uid',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageseries',
            name='study_uid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
